### ISSUE TITLE
Створити і додати map legend

### ISSUE THREAD

**Issue by fedij** [Syopic/worldmap#20]

**Comment by Syopic** [comment]
https://stackblitz.com/edit/berkoworldmapstable

**Comment by fedij** [comment]
https://stackblitz.com/edit/berkoworldmapstable-3uogen

**Comment by TomaGreenFox** [comment]
ГЕС, наш завод, ТЕС, кордон, лесопилка, колхоз, фабрика нікіти (хз як вона називаться)
